### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by jimmyptran95** [hmlendea/iptv-playlist-aggregator#1]
Very useful piece of software you have shared, but it is somewhat overwhelming for your average Joe implement into his setup. Maybe you can make a simple guide on how to run and use the program (or even create a gui if you're up for the challenge). Thanks!

**Comment by hmlendea** [comment]
Hi,

Yes, I can create a guide. I'll do that today,

But the GUI not, since I intended it to be fit as a background service.

Of coruse, if anyone else wants to implement that, they are free to do so and to open a pull request which I'll be happy to review and approve.

**Comment by hmlendea** [comment]
The README.md was updated with the necessary instructions.

A repo Wiki is considered for the future, as a place where to put more detailed information
