### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by staycanuca** [hmlendea/iptv-playlist-aggregator#32]
|FATAL|Operation=Unknown,OperationStatus=FAILURE,Exception=System.Collections.Generic.KeyNotFoundException,ExceptionMessage=The given key 'educational[' was not present in the dictionary.,StackTrace=   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

Salut. 
Am eroarea de mai sus pe w10 x64

**Comment by hmlendea** [comment]
Hello,

Yes, I've noticed the same error yesterday, but I didn't have the time to fix it. I'm going to solve it today.

Am observat și eu eroarea ieri, dar n-am avut timp să o fixez. O să o rezolv azi.

**Comment by hmlendea** [comment]
Fixed in #33 . Release 2.3.2.1
