### ISSUE TITLE
Question: similar project in Java

### ISSUE THREAD

**Issue by dfernandezm** [hmlendea/iptv-playlist-aggregator#37]
First of all, sorry if this is inappropriate. 

I was thinking in starting a very similar (if not the same) project, but in Java. It would be the first time that I do something kind of exactly copying other thing and I would like to contact and comment on it.

**Comment by hmlendea** [comment]
Hello.

I don't see anything wrong with this. I've made this project open-source for this exact reason, so that other people can reuse my work how they see if, if they want to.

I wish you good luck with the project
