### ISSUE TITLE
Update provider urls for Gratis IPTV

### ISSUE THREAD

**Issue by JBou** [hmlendea/iptv-playlist-aggregator#52]
As seen [here](https://www.gratisiptv.com/romania-top-udp-m3u-stable-list-no-lag-14-oct-2020/), provider url's for gratisiptv have changed from `dl` to `m3u`

`https://gratisiptv.com/dl/ro-gratisiptvm3u-{0:yyyy-MM-dd}-1.m3u`
becomes:
`https://gratisiptv.com/m3u/ro-gratisiptvm3u-{0:yyyy-MM-dd}-1.m3u`

**Comment by JBou** [comment]
oh, just saw they are already included as alternative urls. sorry

**Comment by hmlendea** [comment]
Yeah, I've added them today. I'm not sure if the change from `dl` to `m3u` is permanent or not, that's why I've kept both variants.
